WEAPONS = {
    [`WEAPON_UNARMED`] = { "Player got beaten to death", "beaten" },
    [`WEAPON_KNIFE`] = { "Player has been stabbed", "stabbed" },
    [`WEAPON_NIGHTSTICK`] = { "Player has been hit with a nightstick", "beaten" },
    [`WEAPON_HAMMER`] = { "Player has been struck with a hammer", "stabbed" },
    [`WEAPON_BAT`] = { "Player has been hit with a bat", "beaten" },
    [`WEAPON_GOLFCLUB`] = { "Player has been whacked with a golf club", "beaten" },
    [`WEAPON_CROWBAR`] = { "Player has been struck with a crowbar", "stabbed" },
    [`WEAPON_PISTOL`] = { "Player has been shot with a pistol", "shot" },
    [`WEAPON_COMBATPISTOL`] = { "Player has been shot with a combat pistol", "shot" },
    [`WEAPON_APPISTOL`] = { "Player has been shot with an AP pistol", "shot" },
    [`WEAPON_PISTOL50`] = { "Player has been shot with a .50 pistol", "shot" },
    [`WEAPON_MICROSMG`] = { "Player has been shot with a micro SMG", "shot" },
    [`WEAPON_SMG`] = { "Player has been shot with an SMG", "shot" },
    [`WEAPON_ASSAULTSMG`] = { "Player has been shot with an assault SMG", "shot" },
    [`WEAPON_ASSAULTRIFLE`] = { "Player has been shot with an assault rifle", "shot" },
    [`WEAPON_CARBINERIFLE`] = { "Player has been shot with a carbine rifle", "shot" },
    [`WEAPON_ADVANCEDRIFLE`] = { "Player has been shot with an advanced rifle", "shot" },
    [`WEAPON_MG`] = { "Player has been shot with a machine gun", "shot" },
    [`WEAPON_COMBATMG`] = { "Player has been shot with a combat machine gun", "shot" },
    [`WEAPON_PUMPSHOTGUN`] = { "Player has been shot with a pump shotgun", "shot" },
    [`WEAPON_SAWNOFFSHOTGUN`] = { "Player has been shot with a sawed-off shotgun", "shot" },
    [`WEAPON_ASSAULTSHOTGUN`] = { "Player has been shot with an assault shotgun", "shot" },
    [`WEAPON_BULLPUPSHOTGUN`] = { "Player has been shot with a bullpup shotgun", "shot" },
    [`WEAPON_SNIPERRIFLE`] = { "Player has been shot by a sniper rifle", "shot" },
    [`WEAPON_HEAVYSNIPER`] = { "Player has been shot by a heavy sniper", "shot" },
    [`WEAPON_REMOTESNIPER`] = { "Player has been shot by a remote sniper", "shot" },
    [`WEAPON_GRENADELAUNCHER`] = { "Player has been hit by a grenade launcher", "beaten" },
    [`WEAPON_GRENADE`] = { "Player has been blown up by a grenade", "burn" },
    [`WEAPON_STICKYBOMB`] = { "Player has been blown up by a sticky bomb", "burn" },
    [`WEAPON_MOLOTOV`] = { "Player has been set on fire by a Molotov cocktail", "burn" },
    [`WEAPON_RPG`] = { "Player has been hit by an RPG", "beaten" },
    [`WEAPON_MINIGUN`] = { "Player has been shot with a minigun", "shot" },
    [`WEAPON_GRENADELAUNCHER_SMOKE`] = { "Player has been hit by a smoke grenade launcher", "beaten" },
    [`WEAPON_RAYPISTOL`] = { "Player has been shot by a ray pistol", "shot" },
    [`WEAPON_RAYCARBINE`] = { "Player has been shot by a ray carbine", "shot" },
    [`WEAPON_RAYMINIGUN`] = { "Player has been shot with a ray minigun", "shot" },
    [`WEAPON_RAYSHOTGUN`] = { "Player has been shot with a ray shotgun", "shot" },
    [`WEAPON_RAYASSAULTRIFLE`] = { "Player has been shot with a ray assault rifle", "shot" },


    [-842959696] = { "Player has been fallen to death", "beaten" },
}

-- © 𝐴𝑟𝑖𝑢𝑠 𝐷𝑒𝑣𝑒𝑙𝑜𝑝𝑚𝑒𝑛𝑡
